services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: olgazaglavnova1979/backend-kupipodariday
    env_file: .env
    ports: 
      - "${BACKEND_PORT}:3000"
    networks:
      - internal_network
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: olgazaglavnova1979/frontend-kupipodariday:0.0.2
    env_file: .env
    ports: 
      - "${FRONTEND_PORT}:80"
    networks:
      - external_network
  pg:
    container_name: pg-kupipodariday
    image: postgres:18-alpine
    env_file: .env
    volumes:
      - postgres_data:${PGDATA}
    networks:
      - internal_network
  pg-admin:
    container_name: adminer
    networks:
      - internal_network 
    image: adminer
    ports: 
      - "${ADMINER_PORT}:8080"
    

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge
